// react/react脚手架/02_src_hello/App.js
/**
 * Time:2022/4/30 15:38 36
 * Name:App.js
 * Path:src
 * ProjectName:react脚手架
 * Author:突然
 *
 *  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
 */

// 引入react框架
import React,{Component} from 'react';

// 引入Hello组件
import Hello from './component/Hello';

/// 引入Welcome组件
import Welcome from './component/Welcome';

// 创建暴露组件
export default class App extends Component{
	render () {
		return(
				<div>
					<Hello/>
					<Welcome/>
				</div>
		)
	}
}

// Vue/vue2/02 vue组件化/2 单文件组件/05_src_插件/App.vue
<!--
  ~ Time:2022/4/9 16:35 57
  ~ Name:App.vue
  ~ Path:src
  ~ ProjectName:zxc
  ~ Author:突然
  ~
  ~  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
  -->

<template>
	<div id="App">
		<School/>
		<hr>
		<Student/>
	</div>
</template>

<script>

import School from '@/components/School';
import Student from '@/components/Student';

export default {
	name: 'App',
	data () {
		return {
			name: 'Vue',
		};
	},
	components: {
		Student,
		School,
	},
	methods: {},
};
</script>
<style>
button {
	margin: 20px;
}
</style>
