// react/react脚手架/10_src_Switch使用/App.js
import React, { Component } from 'react';
import { Route ,Switch} from 'react-router-dom';

import About from './psges/About'; // About是路由组件
import Home from './psges/Home';  // About是路由组件
import Header from './component/Header';  // Header是一般组件
import MyNavLink from './component/MyNavLink';
import Test from './psges/Test';

export default class App extends Component {
	render () {
		return (
				<div>
					<div className="row">
						<div className="col-xs-offset-2 col-xs-8">
							<Header/>
						</div>
					</div>
					<div className="row">
						<div className="col-xs-2 col-xs-offset-2">
							<div className="list-group">
								{/* 原生html中，靠 <a> 跳转不同的页面 */}
								{/* <a className="list-group-item active" href="./about.html">About</a>
								<a className="list-group-item" href="./home.html">Home</a> */}
								
								{/* 靠React中靠路由链接实现切换组件 ---- 编写路由链接 */}
								{/* <NavLink activeClassName="box" className="list-group-item" to="/about">About</NavLink>
								<NavLink activeClassName="box" className="list-group-item" to="/home">Home</NavLink> */}
								<MyNavLink to="/about">About</MyNavLink>
								<MyNavLink to="/home">Home</MyNavLink>
							</div>
						</div>
						<div className="col-xs-6">
							<div className="panel">
								<div className="panel-body">
									{/* 注册路由 */}
									<Switch>
										<Route path="/about" component={About}/>
										<Route path="/home" component={Home}/>
										<Route path="/home" component={Test}/>
									</Switch>
								</div>
							</div>
						</div>
					</div>
				</div>
		);
	}
	
}

// Vue/vue2/02 vue组件化/2 单文件组件/24_src_路由的基本使用/App.vue
<template>
	<div id="App">
		<Banner/>
		<div class="row">
			<div class="col-xs-2 col-xs-offset-2">
				<div class="list-group">
					<!-- 原始的html中我们使用a标片实现页面跳转 -->
					<!--<a class="list-group-item active" href="./about.html">About</a>-->
					<!--<a class="list-group-item" href="./home.html">Home</a>-->

					<!--    -->
					<router-link class="list-group-item" active-class="active" to="/about">About</router-link>
					<router-link class="list-group-item" active-class="active" to="/home">Home</router-link>
				</div>
			</div>
			<div class="col-xs-6">
				<div class="panel">
					<div class="panel-body">
						<!-- 指定组件呈现位置 -->
						<router-view></router-view>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
import Banner from '@/components/Banner';

export default {
	name: 'App',
	components: {
		Banner,
	},
};
</script>

<style>
#App {
}
</style>
