// Vue/vue2/02 vue组件化/2 单文件组件/27_src_两新的生命周期/App.vue
<template>
    <div id="App">
        <Banner/>
        <div class="row">
            <div class="col-xs-2 col-xs-offset-2">
                <div class="list-group">
                    <!-- 原始的html中我们使用a标片实现页面跳转 -->
                    <!--<a class="list-group-item active" href="./about.html">About</a>-->
                    <!--<a class="list-group-item" href="./home.html">Home</a>-->

                    <!--    -->
                    <router-link class="list-group-item" active-class="active" to="/about">About</router-link>
                    <router-link class="list-group-item" active-class="active" to="/home">Home</router-link>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="panel">
                    <div class="panel-body">
                        <!-- 指定组件呈现位置 -->
                        <router-view></router-view>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import Banner from '@/components/Banner';

export default {
    name: 'App',
    components: {
        Banner,
    },
};
</script>

<style>
#App {
}
</style>

// react/react脚手架/07_src_路由的基本使用/App.js
import React, { Component } from 'react';
import { Link, Route } from 'react-router-dom';

import About from './component/About';
import Home from './component/Home';

export default class App extends Component {
	render () {
		return (
				<div>
					<div className="row">
						<div className="col-xs-offset-2 col-xs-8">
							<div className="page-header"><h2>React Router Demo</h2></div>
						</div>
					</div>
					<div className="row">
						<div className="col-xs-2 col-xs-offset-2">
							<div className="list-group">
								{/* 原生html中，靠 <a> 跳转不同的页面 */}
								{/* <a className="list-group-item active" href="./about.html">About</a>
								<a className="list-group-item" href="./home.html">Home</a> */}
								
								{/* 靠React中靠路由链接实现切换组件 ---- 编写路由链接 */}
								<Link className="list-group-item" to="/about">About</Link>
								<Link className="list-group-item" to="/home">Home</Link>
							</div>
						</div>
						<div className="col-xs-6">
							<div className="panel">
								<div className="panel-body">
									{/* 注册路由 */}
									<Route path="/about" component={About}/>
									<Route path="/home" component={Home}/>
								</div>
							</div>
						</div>
					</div>
				</div>
		);
	}
	
}
